In [1]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)

[[[0.41503225 0.04324248 0.1047389 ]
  [0.14587587 0.605361   0.71972993]
  [0.50507952 0.96930725 0.52622041]]

 [[0.01973918 0.9208891  0.34526716]
  [0.22820943 0.87281252 0.27778398]
  [0.64056241 0.0985056  0.44575912]]

 [[0.67321764 0.06821635 0.04334487]
  [0.48475855 0.26745558 0.85516182]
  [0.83888537 0.77935726 0.34924118]]]


In [2]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Fill the values 1, 2, 3, and 4 just below the diagonal
for i in range(1, 5):
    matrix[i, i - 1] = i

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [3]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern with 1 and 0
matrix[1::2, ::2] = 1  # Rows 2, 4, 6, 8, Columns 1, 3, 5, 7
matrix[::2, 1::2] = 1  # Rows 1, 3, 5, 7, Columns 2, 4, 6, 8

# Print the checkerboard matrix
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)


Original Random Matrix:
[[0.74307269 0.97253946 0.46366741 0.48948022 0.20133598]
 [0.66745559 0.42256243 0.76888262 0.44266742 0.1257813 ]
 [0.59213784 0.8970792  0.88310025 0.0212273  0.24571968]
 [0.65430544 0.11018392 0.12861138 0.71930215 0.24464135]
 [0.91876538 0.36714616 0.93962717 0.67680518 0.15980956]]

Normalized Matrix:
[[ 0.77410609  1.55034456 -0.17106401 -0.08374462 -1.0584768 ]
 [ 0.51830913 -0.31011361  0.86141572 -0.24210261 -1.31406261]
 [ 0.2635248   1.29507815  1.24779026 -1.66774712 -0.90833594]
 [ 0.4738249  -1.36682531 -1.30448906  0.69369528 -0.91198373]
 [ 1.368438   -0.49757538  1.43900912  0.54993687 -1.19895209]]


In [6]:
import numpy as np

# Create two arrays
array1 = np.array([11, 26, 33, 49, 51])
array2 = np.array([33, 45, 51, 64, 77])

# Find common values between the two arrays using boolean indexing
common_values = array1[np.isin(array1, array2)]

print("Common values:", common_values)

Common values: [33 51]


In [7]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now()

# Calculate yesterday's date by subtracting one day
yesterday = today - timedelta(days=1)

# Calculate tomorrow's date by adding one day
tomorrow = today + timedelta(days=1)

# Format the dates as strings (optional)
today_str = today.strftime('%Y-%m-%d')
yesterday_str = yesterday.strftime('%Y-%m-%d')
tomorrow_str = tomorrow.strftime('%Y-%m-%d')

# Print the dates
print("Yesterday:", yesterday_str)
print("Today:", today_str)
print("Tomorrow:", tomorrow_str)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


In [8]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if the arrays are equal element-wise
elementwise_equal = (A == B).all()

if elementwise_equal:
    print("Arrays A and B are equal element-wise.")
else:
    print("Arrays A and B are not equal element-wise.")

Arrays A and B are not equal element-wise.


In [9]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original random vector:")
print(random_vector)

Original random vector:
[0.53040129 0.02319928 0.43208438 0.6679403  0.71078645 0.18680199
 0.41911675 0.         0.77784439 0.04983637]


In [11]:
my_list = [1, 2, 3, 4, 5]

for value in my_list:
    print(value)


1
2
3
4
5


In [12]:
#Using a list comprehension:

my_list = [1, 2, 3, 4, 5]
[print(value) for value in my_list]

1
2
3
4
5


[None, None, None, None, None]

In [13]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

[1 2 3 4 5]


In [14]:
import numpy as np

# Create a sample matrix (replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the original matrix
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)

print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [15]:
import numpy as np

# Your initial vector
initial_vector = np.array([1, 2, 3, 4, 5])

# Second vector containing indices
indices = np.array([0, 2, 3])

# Create a new vector to store the results
result_vector = initial_vector.copy()

# Add one to each element at the specified indices
result_vector[indices] += 1

print(result_vector)

[2 2 4 5 5]


In [16]:
import numpy as np

# Create two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculate the dot product of A and B
dot_product = np.dot(A, B)

# Get the diagonal elements of the dot product
diagonal = np.diagonal(dot_product)

print(diagonal)

[30 69 90]


In [17]:
import numpy as np

# Sample array
my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])

# Use the `unique` function to get unique values and their counts
unique_values, counts = np.unique(my_array, return_counts=True)

# Find the index of the maximum count, which corresponds to the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_values[most_frequent_index]

print(f"The most frequent value is {most_frequent_value} with {counts[most_frequent_index]} occurrences.")

The most frequent value is 4 with 4 occurrences.


In [18]:
import numpy as np

# Create an example array
arr = np.array([5, 2, 8, 1, 7, 3])

# Set the value of 'n' to get the n-largest values
n = 3

# Use partition to get the n-largest values
n_largest = np.partition(arr, -n)[-n:]

print(n_largest)

[5 7 8]


In [21]:
import numpy as np

# Create a regular array with data
regular_array = np.array([(1, 'Alice', 25),
                           (2, 'Bob', 30),
                           (3, 'Charlie', 22)],
                          dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Create a record array
record_array = np.rec.fromarrays(regular_array.T, names=regular_array.dtype.names)

# Print the record array
print(record_array)

((1, 'Alice', 25), (2, 'Bob', 30), (3, 'Charlie', 22))


In [22]:
import numpy as np

# Create a sample 2D NumPy array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows (for example, swapping rows 0 and 2)
array[[0, 2]] = array[[2, 0]]

# Now, 'array' will have rows 0 and 2 swapped
print(array)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [23]:
import numpy as np

# Create a NumPy array
original_array = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to the next dimension
reshaped_array = original_array.reshape(-1, original_array.shape[0])

# Print the original and reshaped arrays
print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped Array:
[[1 2 3]
 [4 5 6]]
